---
apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: Pattern
metadata:
  name: mgmt-vpatterns
  namespace: openshift-operators
spec:
  clusterGroupName: hub
  gitSpec:
    targetRepo: https://github.com/jtovarro/hub-blank-vpattern.git
    targetRevision: gmbros
  gitOpsSpec:
    operatorChannel: gitops-1.11
    operatorSource: redhat-operators
  multiSourceConfig:
    enabled: false
    clusterGroupChartGitRevision: gmbros
